### ISSUE TITLE
tar missing 'z'

### ISSUE THREAD

**Issue by vanhauser-thc** [ernw/static-toolbox#6]
gdb build:

```
Run /bin/sh -c "cd / && curl -so ${ARCH}-cross.tgz ${HOST}/${ARCH}-cross.tgz && tar -xf ${ARCH}-cross.tgz && rm ${ARCH}-cross.tgz && cd ${ARCH}-cross"
```
needs to be `tar -xzf`

**Comment by vanhauser-thc** [comment]
@nschiess

**Comment by takeshixx** [comment]
That's actually not necessary. Since [v1.15](http://www.gnu.org/software/tar/) tar does that automatically:

> Compressed archives are recognised automatically, it is no longer necessary to specify -Z, -z, or -j options to read them. Thus, you can now run tar tf archive.tar.gz and expect it to work!

**Comment by vanhauser-thc** [comment]
well the build system was complaining that it could not identify the file, but maybe you just had to fix the path. lets see if it builds now :)

**Comment by vanhauser-thc** [comment]
works now, thanks!

**Comment by takeshixx** [comment]
You are right, but the actual bug was even more dumb: the download URL for musl changed, so it basically complained because curl was creating an empty file... :facepalm:

I'm currently working on fixing the other issues and introducing some changes to make it more convenient to access to build artifacts. I will update the state in #5 as soon as I'm done.
